apiVersion: v1
kind: Pod
metadata:
  name: kubescope-cli
spec:
  containers:
  - image: hharnisc/kube-scope-cli:9c02f636b8cb6d4f251af3e73d19248c2a31b3e1
    name: kubescope-cli
    stdin: true
    tty: true
    volumeMounts:
    - mountPath: /var/run/docker.sock
      name: docker-sock-volume
    env:
    - name: MATCH_NAME
      value: ".*k8s-dashboard-kubernetes-dashboard.*"
    # (optional) match on a specific docker image
    # - name: MATCH_IMAGE
    #   value: ".*my-image.*"
    # (optional) skip with a specific name
    # - name: SKIP_NAME
    #   value: ".*POD.*"
    # (optional) skip with a specific docker image
    # - name: SKIP_IMAGE
    #   value: ".*POD.*"
    # - name: DOCKER_SOCKET
    #   value: /var/run/docker.sock
  volumes:
  - name: docker-sock-volume
    hostPath:
      path: /var/run/docker.sock
  # pin kubescope to a specific node
  nodeSelector:
    kubernetes.io/hostname: taeho-k8s-2nd-d839df-k8s-worker-2
